Exercice 1 : Introduction à l'analyse des données (Facile)


Objectif : Comprendre les principes de base et l'importance de l'analyse des données.
Tâche:
Rédigez un court essai ou rapport sur les sujets suivants :

Qu'est-ce que l'analyse de données ?
Pourquoi l'analyse des données est-elle importante dans les contextes modernes ?
Citez et décrivez trois domaines d'application actuels de l'analyse de données.

L'analyse de données consiste à collecter des données brutes et disparates à partir de sources diverses, les traiter, c'est-à-dire les nettoyer et garder les plus pertinentes et exploitables. on interprétera ensuite ces données retenues pour prendre des décisions en vue d'optimiser ou améliorer une activité ou résoudre un problème posé.

C'est important aujourd'hui en raison du volume de données explosif qu'il y a dans chaque domaine, leur traitement s'impose pour affiner le canevas de prises de décisions et augmenter l'efficacité humaine. En se basant sur ce qui a déjà été, il est plus facile d'appréhender l'avenir. Elle transforme ainsi l'intuition en décision éclairée.

l'analyse de données est appliquée dans le domaine de la santé. Se référer au comportement ancien de pandémie et des réactions d'antan pour anticiper sur les prochaines et prendre les bonnes décisions comme dans le cas de la COVID-19.
Dans le domaine de l'entertainment, les applications comme Netflix utilisent les données de viosnnage et de préférences pour recommander des contenus personnalisés, augmentant ainsi la retention des abonnés.
Dans le domaine commercial aussi, Les grandes enseignes analysent les données d'achats pour optimiser la disposition des produits en magasin, gérer les stocks et anticiper la demande saisonnière."

Exercice 2 : Chargement et analyse initiale des données


Objectif : S'exercer au chargement de jeux de données depuis Kaggle et à l'analyse initiale.

Chargez l'ensemble de données dans Jupyter ou Google Colab.
Afficher les premières lignes.
Veuillez fournir une brève description de l'ensemble de données.

In [ ]:
!unzip /content/'Credit Card Approvals (Clean Data)'.zip

Archive:  /content/Credit Card Approvals (Clean Data).zip
  inflating: Credit Card Approvals (Clean Data)/clean_dataset.csv
  inflating: Credit Card Approvals (Clean Data)/crx.csv

In [ ]:
import os
os.listdir('/content/Global Trends in Mental Health Disorder')

['Mental health Depression disorder Data.csv']

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Global Trends in Mental Health Disorder/Mental health Depression disorder Data.csv')
df.head()

/tmp/ipykernel_5443/3488545048.py:2: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/Global Trends in Mental Health Disorder/Mental health Depression disorder Data.csv')

,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260

Ce tableau contient des données annuelles liées à la santé mentale, notamment aux troubles du sommeil et à la dépression.
Chaque ligne représente une observation pour une année donnée.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/How Much Sleep Do Americans/Time Americans Spend Sleeping.csv')
df.head()

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

Ce tableau contient des statistiques annuelles sur le temps de sommeil des Américains.
Chaque ligne représente des données observées pour une année donnée.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Credit Card Approvals (Clean Data)/clean_dataset.csv')
df.head()

,Gender,Age,Debt,Married,BankCustomer,Industry,Ethnicity,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,1,30.83,0.000,1,1,Industrials,White,1.25,1,1,1,0,ByBirth,202,0,1
1,0,58.67,4.460,1,1,Materials,Black,3.04,1,1,6,0,ByBirth,43,560,1
2,0,24.50,0.500,1,1,Materials,Black,1.50,1,0,0,0,ByBirth,280,824,1
3,1,27.83,1.540,1,1,Industrials,White,3.75,1,1,5,1,ByBirth,100,3,1
4,1,20.17,5.625,1,1,Industrials,White,1.71,1,0,0,0,ByOtherMeans,120,0,1

Ce tableau contient des informations financières et personnelles utilisées pour prédire l’acceptation ou non d’une demande de carte de crédit.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Credit Card Approvals (Clean Data)/crx.csv')
df.head()

   b  30.83      0  u  g  w  v  1.25  t t.1  01  f g.1  00202  0.1  +
0  a  58.67  4.460  u  g  q  h  3.04  t   t   6  f   g  00043  560  +
1  a  24.50  0.500  u  g  q  h  1.50  t   f   0  f   g  00280  824  +
2  b  27.83  1.540  u  g  w  v  3.75  t   t   5  t   g  00100    3  +
3  b  20.17  5.625  u  g  w  v  1.71  t   f   0  f   s  00120    0  +
4  b  32.08  4.000  u  g  m  v  2.50  t   f   0  t   g  00360    0  +

Exercice 3 : Identification des types de données


Objectif : Apprendre à identifier les différents types de données.
Tâche:
Pour les ensembles de données de l'exercice précédent, catégorisez chaque colonne comme quantitative ou qualitative et expliquez votre raisonnement.

Les colonnes : Entity, Period, Type of days, activity, sex, industry, ethnicity and cityzen sont des données qualitatives car ce sont des données non mesurables.

les autres colonnes sont des données quantitatives car elles sont numériques, elles sont numériques et quantifiables.

Exercice 4 : Exploration des types de données


Objectif : Découvrir les différents types de données en analyse de données.

In [ ]:
!unzip /content/'Iris Dataset'.zip

Archive:  /content/Iris Dataset.zip
  inflating: Iris Dataset/Iris.csv

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Iris Dataset/Iris.csv')
df.head(10)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

La seule colonne qualitative est la colonne Species (espèce de la fleur Iris) car ele contient des catégories Setosa, versicolor...

Toutes les autres colonnes : SepalLenghCm, SepalWidthCm, PetalLenghCm, PetalWidthCm et Id sont quantitatives car elles contiennent des valeurs numériques mesurées en cm pour certaines et pour l'Id, la valeur est utilisée pour identifier chaque observation.

Exercice 5 : Compétences d’observation de base en analyse de données


Objectif : Développer des compétences d’observation pour l’analyse des données

In [ ]:
import pandas as pd
!unzip /'How Much Sleep Do Americans'.zip

Archive:  /How Much Sleep Do Americans.zip
  inflating: How Much Sleep Do Americans/Time Americans Spend Sleeping.csv

In [ ]:
import pandas as pd
df = pd.read_csv('/content/How Much Sleep Do Americans/Time Americans Spend Sleeping.csv')
df.head()

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

Les colonnes qui pourraient être intéressantes pour un type spécifique d'analyse sont les colonnes "Avg per days sleeping", "Standard error" et "Age group". les deux premières colonnes sont des données quantitatives et vairiables donc permettront d'analyser des tendances avec des chiffres et la dernière colonne permettra de faire des regroupements.

Exercice 6 : Identification des types de données
Voici différentes sources de données. Identifiez si chacune est un exemple de données structurées ou non structurées.


Les rapports financiers d’une entreprise stockés dans un fichier Excel: données structurées
Photographies téléchargées sur une plateforme de réseaux sociaux : données non structurées.
Une collection d’articles d’actualité sur un site web : données non structurées.
Données d’inventaire dans une base de données relationnelle: données structurées.
Interviews enregistrées issues d’une étude de marché : données non structurées

Exercice 7 : Exercice de transformation
Pour chacune des sources de données non structurées suivantes, proposez une méthode pour les convertir en données structurées. Expliquez votre raisonnement.

Une série d’articles de blog sur les expériences de voyage.
Methode proposée : utilisation du Tratement de Langage Naturel (NLP).
les articles de blog étant du texte libre et non organisé, le NLP permettra d'identifier automatiquement : les lieux visités, les dates, les émotions, les activités qui pourront constituer, avec l'auteur de l'article, les colonnes d'un tableau exploitable pour l'analyse statistique ou les recommandations

Enregistrements audio d’appels du service client.

methode proposée: utilisation de reconnaissance vocale + NLP.
Les enregistrements audios sont des mots non structurés sous forme audio. Il faut donc les retranscrire en texte à partir du Speech-to-Text et ensuite appliquer le NLP qui pourra détecter les plaintes fréquentes, classifier les demandes et évaluer les sentiments du client.

Des notes manuscrites d’une séance de brainstorming.
Dans ce cas, l'OCR est la méthode adaptée.
Il va convertir l'écriture en texte numérique compréhensible et analysable par l'ordinateur qui pourra ensuite classer les informations par thème ou importance.

Un tutoriel vidéo sur la cuisine.
La transcription du texte et la vision par ordinateur constitueront la méthode utilisée.
il faudra d'abord extraire les informations contenues dans la vidéo qui sont de différents types avant de les classifier.

Exercice 8 : Importer un fichier depuis Kaggle
Note : Ce jeu de données provenait à l’origine de Kaggle, mais pour un accès plus facile, il a été mis à disposition sur GitHub.

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"
df = pd.read_csv(url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Exercice 9 : Exportez une dataframe en format Excel et JSON.
Créez un dataframe simple.
Exportez la dataframe dans un fichier Excel.
Exportez la dataframe en fichier JSON.

In [ ]:
import pandas as pd
Data=  {
    'Nom': ['Chris', 'Mouahe', 'KOUAKOU'],
    'Age': [24, 17, 9],
    'commune': ['Cocody', 'Yamoussoukro', 'Yopougon']
}
df = pd.DataFrame(Data)
df.to_excel('data.xlsx')
df.to_json('data.json')

       Nom  Age       commune
0    Chris   24        Cocody
1   Mouahe   17  Yamoussoukro
2  KOUAKOU    9      Yopougon

Exercice 10 : Lecture des données JSON
Utilisez un jeu de données JSON d’exemple

In [ ]:
!unzip /posts.zip

Archive:  /posts.zip
  inflating: posts.json

In [ ]:
import pandas as pd
data_json = pd.read_json('posts.json')
df.head()

       Nom  Age       commune
0    Chris   24        Cocody
1   Mouahe   17  Yamoussoukro
2  KOUAKOU    9      Yopougon

In [17]:
!cp Exercice_XP.ipynb /content/TTA-Bootcamp-GenAI/

cp: cannot stat 'Exercice_XP.ipynb': No such file or directory